[package]
name = "hax-adt-into"
edition = "2024"
version = "0.3.5"
authors = ["hax Authors"]
license = "Apache-2.0"
homepage = "https://github.com/hacspec/hax"
description = "Provides the `adt_into` procedural macro, allowing for mirroring data types with small variations."

[lib]
proc-macro = true

[dependencies]
itertools = "0.11.0"
syn = { version = "1.0.107", features = [
     "derive",
     "printing",
     "extra-traits",
     "parsing",
     "full",
] }
proc-macro2 = "1.0"
quote = "1.0"

[dev-dependencies]
tracing = { version = "0.1", features = [
     "max_level_trace",
     "release_max_level_trace",
] }
